config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  root to: 'page#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, type: String
  field :text, type: String
  field :tags, type: Array
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :text, :tags)
    end
end

app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = GenBlogSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue => e
    raise e unless Rails.env.development?
    handle_error_in_development e
  end

  private

  # Handle form data, JSON body, or a blank value
  def ensure_hash(ambiguous_param)
    case ambiguous_param
    when String
      if ambiguous_param.present?
        ensure_hash(JSON.parse(ambiguous_param))
      else
        {}
      end
    when Hash, ActionController::Parameters
      ambiguous_param
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { error: { message: e.message, backtrace: e.backtrace }, data: {} }, status: 500
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/blogs/_form.html.haml
= form_for @blog do |f|
  - if @blog.errors.any?
    #error_explanation
      %h2= "#{pluralize(@blog.errors.count, "error")} prohibited this blog from being saved:"
      %ul
        - @blog.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :text
    = f.text_field :text
  .field
    = f.label :tags
    = f.text_field :tags
  .actions
    = f.submit 'Save'

app/views/blogs/edit.html.haml
%h1 Editing blog

= render 'form'

= link_to 'Show', @blog
\|
= link_to 'Back', blogs_path

app/views/blogs/index.html.haml
%h1 Listing blogs

%table
  %thead
    %tr
      %th Title
      %th Text
      %th Tags
      %th
      %th
      %th

  %tbody
    - @blogs.each do |blog|
      %tr
        %td= blog.title
        %td= blog.text
        %td= blog.tags
        %td= link_to 'Show', blog
        %td= link_to 'Edit', edit_blog_path(blog)
        %td= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Blog', new_blog_path

app/views/blogs/new.html.haml
%h1 New blog

= render 'form'

= link_to 'Back', blogs_path

app/views/blogs/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @blog.title
%p
  %b Text:
  = @blog.text
%p
  %b Tags:
  = @blog.tags

= link_to 'Edit', edit_blog_path(@blog)
\|
= link_to 'Back', blogs_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title GenBlog
    = csrf_meta_tags
    = csp_meta_tag
    -# %link{:href => 'https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900|Material+Icons', :rel => "stylesheet"}
    -# %link{:href => 'https://cdn.jsdelivr.net/npm/vuetify/dist/vuetify.min.css', :rel => "stylesheet"}
    -# = stylesheet_link_tag 'application'
  %body
    = yield
    = javascript_pack_tag 'application'

app/views/page/home.html.haml
#app